name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        description: "Version to deploy"
        required: true
      bootstrap:
        description: "Bootstrap the stack"
        required: false
        default: "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  actions: write
  contents: read

jobs:
  saga:
    runs-on: ubuntu-latest

    environment: production

    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      STACK_PREFIX: ${{ vars.STACK_PREFIX }}
      BASE_DOMAIN_NAME: ${{ vars.BASE_DOMAIN_NAME }}

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Determine released version
        id: version
        run: |
          git fetch --tags
          VERSION=`git describe --abbrev=0 --tags --always | tr -d '\n'`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Cache AWS CLI (Linux)
        id: cache-aws-cli
        uses: actions/cache@v4
        with:
          path: aws/
          key: cache-aws-cli

      - name: Install AWS
        if: steps.cache-aws-cli.outputs.cache-hit != 'true'
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: |-
            arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.STACK_PREFIX }}-cd-cd
          role-session-name: gh-actions-publish
          aws-region: ${{ env.AWS_REGION }}

      - name: Bootstrap the stack
        if: ${{ github.event.inputs.bootstrap == 'true' }}
        env:
          NODE_OPTIONS: "--experimental-transform-types --no-warnings"
        run: |
          npx cdk --app "node cdk/prod.ts" bootstrap

      - name: Diff
        env:
          NODE_OPTIONS: "--experimental-transform-types --no-warnings"
        run: |
          npx cdk --app "node cdk/prod.ts" diff --all

      - name: Deploy to AWS
        env:
          NODE_OPTIONS: "--experimental-transform-types --no-warnings"
        run: |
          npx cdk --app "node cdk/prod.ts" deploy --require-approval never --all
